_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 103
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
batch_size:
    value: 16
encoder_checkpoint:
    value: normtverskyloss_binary_segmentation
info:
    value: Training without PyTorch Lightning
input_dim:
    value: 256x256:64
k_fold:
    value: 5
model_type:
    value: BinaryClassificationTorch
radiomics:
    value: false
