_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 103
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
